### ISSUE TITLE
需要修改的配置文件是哪个?

### ISSUE THREAD

**Issue by zstdh777** [holmofy/debezium-datetime-converter#3]
需要修改的配置文件是哪个?

**Comment by holmofy** [comment]
有两种方式配置，单机版和集群版方式不一样，具体可以参考我写的这篇[文章](https://blog.hufeifei.cn/2021/03/DB/mysql-binlog-parser/#4-2-zhun-bei-kafka-huan-jing-zai-kafka-connect-zhong-an-zhuang-debezium)

[这里有个我之前配好的现成的例子](https://github.com/holmofy/docker-compose/blob/main/darcy-kafka-connect/kafka-connect/hermes01-debezium.properties)
